### PR TITLE
Add settings menu

### PR DESCRIPTION
**Pull request by dommilosz**
I'm working on settings menu as you mentioned in the TODOs (make energy, speed and feed customisable. For now I've made simple settings menu as your About menu. The settings are stored in localstorage. 
image

Don't merge it just yet, it's still WIP. Do you have any knowledge or resources on what is the range of these parameters, or in what units are they? I'll be implementing some settings from the Cat-Printer.

I'm looking forward for your suggestions or edits.

### CODE REVIEW

**Comment by NaitLee** [comment]
In my mind the settings (or say “print options”) button is beside print, to say the options are related to printing:

```
┌──────────────────────────────────────────────────┐
│                 (preview paper)                  │
└──────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────┐
│               (expandable settings)              │
└──────────────────────────────────────────────────┘
╭────────────────╮╭────────────────────────────────╮
│       ⚙️       ││               🖨️               │
╰────────────────╯╰────────────────────────────────╯
```

And the “settings” near “about” could be some application-related settings instead.

For range of these values, you may see related methods in [cat-protocol.ts](https://github.com/NaitLee/kitty-printer/blob/main/common/cat-protocol.ts). Let’s say:
```ts
    feed(points: number) {
        return this.send(this.make(Command.Feed, bytes(points, 2)));
    }
```
The `bytes(points, 2)` indicates the “feed” value may be 0-65535 (2^16 - 1).
Otherwise, if it’s barely `bytes(points)`, assume it’s 0-255 (2^8 - 1).

The “feed” unit is, well, dots. These printers have 4.8cm (~1.889 inches) for 384 dots, that’s about 203 DPI.
Maybe add a ruler/slider for that option…
The speed is, “the lower the quicker”. Recommended no less than 8, and 40 would be somewhat slow. 3 or 4 choices are enough.
Speed affects print quality, for heat stability I think.
The energy could be a few choices too. I name it “strength”, like from “light” to “heavy”.

**Comment by dommilosz** [comment]
What do you think?
image

I tried to make some presets, the energy one is the most abstract for me, I'll try experimenting with it.

**Comment by dommilosz** [comment]
I don't really see a difference in the settings other than the feed on my MX06. I even tried energy 1000 and 65535, it looks the same. I also don't see a difference between speeds, speed 8, 16, 32 and 255

**Comment by dommilosz** [comment]
As for the feed, on my printer 50 is about the distance between the head and the opening.

**Comment by NaitLee** [comment]
Probably the `useLocalStorage` didn’t sync the options. The `print` function is inside a closure, for being async.
For that piece of code, reading local storage on demand is okay, I think.
After touching the options, try refresh the page, and it worked.

**Comment by NaitLee** [comment]
oh okay you got that :)

**Comment by dommilosz** [comment]
Great timing :)

**Comment by dommilosz** [comment]
Here are some of my tests. Energy seems to have the darkest @ 16-32k
The speed didn't show much of a difference at all.

IMG_20231227_133000
IMG_20231227_132922
IMG_20231227_132908
IMG_20231227_133008

**Comment by NaitLee** [comment]
The difference of “speed” is indicated by the noise pitch on printing, especially when printing blank. Quality effect of speed is notable when printing usual pictures.

The speed option works here.

**Comment by dommilosz** [comment]
So what do you think the presets should be? Do you have any particular values in mind for all of the settings? Do you have any other suggestions? I'll try to add persistent printer to not have to select the printer every time.

**Comment by dommilosz** [comment]
I see on sticky paper it needs more power like 40k, so I'll adjust the presets low: 16k, medium: 24k, high: 48k

**Comment by NaitLee** [comment]
Just had time to review this. Thank you!

**Pull request merged**
